version: "3.9"

services:
  api:
    build: .
    container_name: secure-artifact-vault
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - artifact_data:/data/artifacts
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: artifact-db
    environment:
      POSTGRES_DB: artifact_vault
      POSTGRES_USER: artifact_user
      POSTGRES_PASSWORD: artifact_pass
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  artifact_data:
  pg_data:
