"""add checksum to artifacts

Revision ID: 9c6d17c204ca
Revises: 9c56c0487ed3
Create Date: 2026-01-12 12:15:45.932454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c6d17c204ca'
down_revision: Union[str, Sequence[str], None] = '9c56c0487ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts', sa.Column('checksum', sa.String(length=64), nullable=False))
    op.alter_column('artifacts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('artifacts', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('artifacts', 'checksum')
    # ### end Alembic commands ###
